vich_uploader:
    db_driver: orm

    mappings:
       property_image:
           uri_prefix: /media/properties
           upload_destination: '%kernel.project_dir%/public/media/cache/resolve/thumb/media/properties'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
